version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: >
      postgres
      -c log_statement=all
      -c log_min_duration_statement=0
      -c log_line_prefix='%t: '
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vectordb"]
      interval: 5s
      timeout: 5s
      retries: 5

  rag-app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./documents:/app/documents
      - ./data:/app/data
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@postgres:5432/vectordb
    stdin_open: true
    tty: true

volumes:
  postgres_data:
